// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czrmbovugjbxbxgbxaxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6cm1ib3Z1Z2pieGJ4Z2J4YXh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMDU3MDgsImV4cCI6MjA3MTY4MTcwOH0.wOIN2O_ROpdTofE5bOW3Bj2ifqtQPQDetS1v00xjaDs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});